name: intel-attack-m
channels:
  - pytorch
  - nvidia
  - intel
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asn1crypto=1.5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - chardet=5.1.0
  - charset-normalizer=3.1.0
  - colorama=0.4.6
  - comm=0.1.2
  - conda-package-streaming=0.8.0
  - cryptography=41.0.1
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.3.52
  - cuda-runtime=12.1.0
  - cycler=0.11.0
  - cython=0.29.35
  - daal4py=2023.2.1
  - dal=2023.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - dpcpp-cpp-rt=2023.2.0
  - dpcpp-llvm-spirv=2023.2.0
  - dpcpp_cpp_rt=2023.2.0
  - dpctl=0.14.5
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - ffmpeg=4.3
  - filelock=3.9.0
  - fortran_rt=2023.2.0
  - freetype=2.12.1
  - funcsigs=1.0.2
  - future=0.18.3
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - icc_rt=2023.2.0
  - icu=72.1
  - idna=3.4
  - impi_rt=2021.10.0
  - intel-cmplr-lib-rt=2023.2.0
  - intel-cmplr-lic-rt=2023.2.0
  - intel-fortran-rt=2023.2.0
  - intel-opencl-rt=2023.2.0
  - intel-openmp=2023.2.0
  - intelpython=2023.2.0
  - intelpython3_core=2023.2.0
  - intelpython3_full=2023.2.0
  - ipp=2021.9.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jsonpatch=1.32
  - jsonpointer=2.0
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - jupyterlab_widgets=3.0.5
  - kiwisolver=1.4.4
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - level-zero=1.11.0
  - libabseil=20230125.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.8.0.34
  - libcurand=10.3.4.52
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.8
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libllvm14=14.0.6
  - libnpp=12.0.2.50
  - libnsl=2.0.0
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libprotobuf=4.23.2
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libstdcxx-ng=12.2.0
  - libtasn1=4.19.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.11.4
  - libzlib=1.2.13
  - llvm=14.0.6
  - llvm-openmp=14.0.6
  - llvm-spirv=14.0.0
  - llvmlite=0.40.0
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mkl=2023.2.0
  - mkl-dpcpp=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mkl_umath=0.1.1
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - networkx=3.1
  - numba=0.57.0
  - numba-dpex=0.21.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.1.1
  - packaging=23.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.1.2
  - platformdirs=3.6.0
  - pluggy=1.0.0
  - pooch=1.7.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyparsing=3.1.0
  - pysocks=1.7.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2023.3
  - pyyaml=6.0
  - pyzmq=25.1.0
  - readline=8.2
  - requests=2.31.0
  - ruamel.yaml=0.17.32
  - ruamel.yaml.clib=0.2.7
  - scikit-learn=1.2.2
  - scikit-learn-intelex=2023.2.1
  - scipy=1.10.1
  - setuptools=67.7.2
  - six=1.16.0
  - smp=0.1.5
  - snappy=1.1.10
  - spirv-tools=2023.2
  - stack_data=0.2.0
  - sympy=1.11.1
  - tbb=2021.10.0
  - tbb4py=2021.10.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - toolz=0.12.0
  - torchaudio=2.1.0
  - torchtriton=2.1.0
  - torchvision=0.16.0
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - urllib3=2.0.3
  - wcwidth=0.2.5
  - wheel=0.40.0
  - widgetsnbextension=4.0.5
  - xgboost=1.7.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - dpnp==0.12.1
      - z3-solver==4.12.2.0
